adjective = input("Enter an adjective: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
adverb = input("Enter an adverb: ")
print("A", adjective, noun, "should never", verb, adverb)
print("Generally, people who", verb, adverb, ", enjoy waching a", adjective, noun, "on the TV")